# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: request.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("request.proto", :syntax => :proto3) do
    add_message "distribuidos.Request" do
      optional :comando, :string, 1
      optional :tipo_da_msg, :string, 2
      optional :nome_do_disp, :string, 3
      optional :nome_da_func, :string, 4
      optional :valor, :int32, 5
    end
    add_message "distribuidos.Response" do
      optional :tipo_da_msg, :string, 1
      optional :conteudo, :string, 2
    end
  end
end

module Distribuidos
  Request = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("distribuidos.Request").msgclass
  Response = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("distribuidos.Response").msgclass
end
