// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: request.proto

package protobuff;

public final class RequestOuterClass {
  private RequestOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuff.Request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string comando = 1;</code>
     * @return The comando.
     */
    java.lang.String getComando();
    /**
     * <code>string comando = 1;</code>
     * @return The bytes for comando.
     */
    com.google.protobuf.ByteString
        getComandoBytes();

    /**
     * <code>string tipo_da_msg = 2;</code>
     * @return The tipoDaMsg.
     */
    java.lang.String getTipoDaMsg();
    /**
     * <code>string tipo_da_msg = 2;</code>
     * @return The bytes for tipoDaMsg.
     */
    com.google.protobuf.ByteString
        getTipoDaMsgBytes();

    /**
     * <code>string nome_do_disp = 3;</code>
     * @return The nomeDoDisp.
     */
    java.lang.String getNomeDoDisp();
    /**
     * <code>string nome_do_disp = 3;</code>
     * @return The bytes for nomeDoDisp.
     */
    com.google.protobuf.ByteString
        getNomeDoDispBytes();

    /**
     * <code>string nome_da_func = 4;</code>
     * @return The nomeDaFunc.
     */
    java.lang.String getNomeDaFunc();
    /**
     * <code>string nome_da_func = 4;</code>
     * @return The bytes for nomeDaFunc.
     */
    com.google.protobuf.ByteString
        getNomeDaFuncBytes();

    /**
     * <code>int32 valor = 5;</code>
     * @return The valor.
     */
    int getValor();
  }
  /**
   * Protobuf type {@code protobuff.Request}
   */
  public  static final class Request extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protobuff.Request)
      RequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Request.newBuilder() to construct.
    private Request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Request() {
      comando_ = "";
      tipoDaMsg_ = "";
      nomeDoDisp_ = "";
      nomeDaFunc_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Request();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              comando_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              tipoDaMsg_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              nomeDoDisp_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              nomeDaFunc_ = s;
              break;
            }
            case 40: {

              valor_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuff.RequestOuterClass.internal_static_protobuff_Request_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuff.RequestOuterClass.internal_static_protobuff_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuff.RequestOuterClass.Request.class, protobuff.RequestOuterClass.Request.Builder.class);
    }

    public static final int COMANDO_FIELD_NUMBER = 1;
    private volatile java.lang.Object comando_;
    /**
     * <code>string comando = 1;</code>
     * @return The comando.
     */
    public java.lang.String getComando() {
      java.lang.Object ref = comando_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        comando_ = s;
        return s;
      }
    }
    /**
     * <code>string comando = 1;</code>
     * @return The bytes for comando.
     */
    public com.google.protobuf.ByteString
        getComandoBytes() {
      java.lang.Object ref = comando_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        comando_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIPO_DA_MSG_FIELD_NUMBER = 2;
    private volatile java.lang.Object tipoDaMsg_;
    /**
     * <code>string tipo_da_msg = 2;</code>
     * @return The tipoDaMsg.
     */
    public java.lang.String getTipoDaMsg() {
      java.lang.Object ref = tipoDaMsg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tipoDaMsg_ = s;
        return s;
      }
    }
    /**
     * <code>string tipo_da_msg = 2;</code>
     * @return The bytes for tipoDaMsg.
     */
    public com.google.protobuf.ByteString
        getTipoDaMsgBytes() {
      java.lang.Object ref = tipoDaMsg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tipoDaMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NOME_DO_DISP_FIELD_NUMBER = 3;
    private volatile java.lang.Object nomeDoDisp_;
    /**
     * <code>string nome_do_disp = 3;</code>
     * @return The nomeDoDisp.
     */
    public java.lang.String getNomeDoDisp() {
      java.lang.Object ref = nomeDoDisp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nomeDoDisp_ = s;
        return s;
      }
    }
    /**
     * <code>string nome_do_disp = 3;</code>
     * @return The bytes for nomeDoDisp.
     */
    public com.google.protobuf.ByteString
        getNomeDoDispBytes() {
      java.lang.Object ref = nomeDoDisp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nomeDoDisp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NOME_DA_FUNC_FIELD_NUMBER = 4;
    private volatile java.lang.Object nomeDaFunc_;
    /**
     * <code>string nome_da_func = 4;</code>
     * @return The nomeDaFunc.
     */
    public java.lang.String getNomeDaFunc() {
      java.lang.Object ref = nomeDaFunc_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nomeDaFunc_ = s;
        return s;
      }
    }
    /**
     * <code>string nome_da_func = 4;</code>
     * @return The bytes for nomeDaFunc.
     */
    public com.google.protobuf.ByteString
        getNomeDaFuncBytes() {
      java.lang.Object ref = nomeDaFunc_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nomeDaFunc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VALOR_FIELD_NUMBER = 5;
    private int valor_;
    /**
     * <code>int32 valor = 5;</code>
     * @return The valor.
     */
    public int getValor() {
      return valor_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getComandoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, comando_);
      }
      if (!getTipoDaMsgBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, tipoDaMsg_);
      }
      if (!getNomeDoDispBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, nomeDoDisp_);
      }
      if (!getNomeDaFuncBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, nomeDaFunc_);
      }
      if (valor_ != 0) {
        output.writeInt32(5, valor_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getComandoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, comando_);
      }
      if (!getTipoDaMsgBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, tipoDaMsg_);
      }
      if (!getNomeDoDispBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, nomeDoDisp_);
      }
      if (!getNomeDaFuncBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, nomeDaFunc_);
      }
      if (valor_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, valor_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protobuff.RequestOuterClass.Request)) {
        return super.equals(obj);
      }
      protobuff.RequestOuterClass.Request other = (protobuff.RequestOuterClass.Request) obj;

      if (!getComando()
          .equals(other.getComando())) return false;
      if (!getTipoDaMsg()
          .equals(other.getTipoDaMsg())) return false;
      if (!getNomeDoDisp()
          .equals(other.getNomeDoDisp())) return false;
      if (!getNomeDaFunc()
          .equals(other.getNomeDaFunc())) return false;
      if (getValor()
          != other.getValor()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + COMANDO_FIELD_NUMBER;
      hash = (53 * hash) + getComando().hashCode();
      hash = (37 * hash) + TIPO_DA_MSG_FIELD_NUMBER;
      hash = (53 * hash) + getTipoDaMsg().hashCode();
      hash = (37 * hash) + NOME_DO_DISP_FIELD_NUMBER;
      hash = (53 * hash) + getNomeDoDisp().hashCode();
      hash = (37 * hash) + NOME_DA_FUNC_FIELD_NUMBER;
      hash = (53 * hash) + getNomeDaFunc().hashCode();
      hash = (37 * hash) + VALOR_FIELD_NUMBER;
      hash = (53 * hash) + getValor();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protobuff.RequestOuterClass.Request parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuff.RequestOuterClass.Request parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuff.RequestOuterClass.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuff.RequestOuterClass.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuff.RequestOuterClass.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuff.RequestOuterClass.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuff.RequestOuterClass.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protobuff.RequestOuterClass.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protobuff.RequestOuterClass.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protobuff.RequestOuterClass.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protobuff.RequestOuterClass.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protobuff.RequestOuterClass.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protobuff.RequestOuterClass.Request prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuff.Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuff.Request)
        protobuff.RequestOuterClass.RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuff.RequestOuterClass.internal_static_protobuff_Request_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuff.RequestOuterClass.internal_static_protobuff_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobuff.RequestOuterClass.Request.class, protobuff.RequestOuterClass.Request.Builder.class);
      }

      // Construct using protobuff.RequestOuterClass.Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        comando_ = "";

        tipoDaMsg_ = "";

        nomeDoDisp_ = "";

        nomeDaFunc_ = "";

        valor_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuff.RequestOuterClass.internal_static_protobuff_Request_descriptor;
      }

      @java.lang.Override
      public protobuff.RequestOuterClass.Request getDefaultInstanceForType() {
        return protobuff.RequestOuterClass.Request.getDefaultInstance();
      }

      @java.lang.Override
      public protobuff.RequestOuterClass.Request build() {
        protobuff.RequestOuterClass.Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public protobuff.RequestOuterClass.Request buildPartial() {
        protobuff.RequestOuterClass.Request result = new protobuff.RequestOuterClass.Request(this);
        result.comando_ = comando_;
        result.tipoDaMsg_ = tipoDaMsg_;
        result.nomeDoDisp_ = nomeDoDisp_;
        result.nomeDaFunc_ = nomeDaFunc_;
        result.valor_ = valor_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuff.RequestOuterClass.Request) {
          return mergeFrom((protobuff.RequestOuterClass.Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobuff.RequestOuterClass.Request other) {
        if (other == protobuff.RequestOuterClass.Request.getDefaultInstance()) return this;
        if (!other.getComando().isEmpty()) {
          comando_ = other.comando_;
          onChanged();
        }
        if (!other.getTipoDaMsg().isEmpty()) {
          tipoDaMsg_ = other.tipoDaMsg_;
          onChanged();
        }
        if (!other.getNomeDoDisp().isEmpty()) {
          nomeDoDisp_ = other.nomeDoDisp_;
          onChanged();
        }
        if (!other.getNomeDaFunc().isEmpty()) {
          nomeDaFunc_ = other.nomeDaFunc_;
          onChanged();
        }
        if (other.getValor() != 0) {
          setValor(other.getValor());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protobuff.RequestOuterClass.Request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protobuff.RequestOuterClass.Request) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object comando_ = "";
      /**
       * <code>string comando = 1;</code>
       * @return The comando.
       */
      public java.lang.String getComando() {
        java.lang.Object ref = comando_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          comando_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string comando = 1;</code>
       * @return The bytes for comando.
       */
      public com.google.protobuf.ByteString
          getComandoBytes() {
        java.lang.Object ref = comando_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          comando_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string comando = 1;</code>
       * @param value The comando to set.
       * @return This builder for chaining.
       */
      public Builder setComando(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        comando_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string comando = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearComando() {
        
        comando_ = getDefaultInstance().getComando();
        onChanged();
        return this;
      }
      /**
       * <code>string comando = 1;</code>
       * @param value The bytes for comando to set.
       * @return This builder for chaining.
       */
      public Builder setComandoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        comando_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object tipoDaMsg_ = "";
      /**
       * <code>string tipo_da_msg = 2;</code>
       * @return The tipoDaMsg.
       */
      public java.lang.String getTipoDaMsg() {
        java.lang.Object ref = tipoDaMsg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          tipoDaMsg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string tipo_da_msg = 2;</code>
       * @return The bytes for tipoDaMsg.
       */
      public com.google.protobuf.ByteString
          getTipoDaMsgBytes() {
        java.lang.Object ref = tipoDaMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tipoDaMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string tipo_da_msg = 2;</code>
       * @param value The tipoDaMsg to set.
       * @return This builder for chaining.
       */
      public Builder setTipoDaMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        tipoDaMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string tipo_da_msg = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTipoDaMsg() {
        
        tipoDaMsg_ = getDefaultInstance().getTipoDaMsg();
        onChanged();
        return this;
      }
      /**
       * <code>string tipo_da_msg = 2;</code>
       * @param value The bytes for tipoDaMsg to set.
       * @return This builder for chaining.
       */
      public Builder setTipoDaMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        tipoDaMsg_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object nomeDoDisp_ = "";
      /**
       * <code>string nome_do_disp = 3;</code>
       * @return The nomeDoDisp.
       */
      public java.lang.String getNomeDoDisp() {
        java.lang.Object ref = nomeDoDisp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nomeDoDisp_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string nome_do_disp = 3;</code>
       * @return The bytes for nomeDoDisp.
       */
      public com.google.protobuf.ByteString
          getNomeDoDispBytes() {
        java.lang.Object ref = nomeDoDisp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nomeDoDisp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string nome_do_disp = 3;</code>
       * @param value The nomeDoDisp to set.
       * @return This builder for chaining.
       */
      public Builder setNomeDoDisp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nomeDoDisp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string nome_do_disp = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearNomeDoDisp() {
        
        nomeDoDisp_ = getDefaultInstance().getNomeDoDisp();
        onChanged();
        return this;
      }
      /**
       * <code>string nome_do_disp = 3;</code>
       * @param value The bytes for nomeDoDisp to set.
       * @return This builder for chaining.
       */
      public Builder setNomeDoDispBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        nomeDoDisp_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object nomeDaFunc_ = "";
      /**
       * <code>string nome_da_func = 4;</code>
       * @return The nomeDaFunc.
       */
      public java.lang.String getNomeDaFunc() {
        java.lang.Object ref = nomeDaFunc_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nomeDaFunc_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string nome_da_func = 4;</code>
       * @return The bytes for nomeDaFunc.
       */
      public com.google.protobuf.ByteString
          getNomeDaFuncBytes() {
        java.lang.Object ref = nomeDaFunc_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nomeDaFunc_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string nome_da_func = 4;</code>
       * @param value The nomeDaFunc to set.
       * @return This builder for chaining.
       */
      public Builder setNomeDaFunc(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nomeDaFunc_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string nome_da_func = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearNomeDaFunc() {
        
        nomeDaFunc_ = getDefaultInstance().getNomeDaFunc();
        onChanged();
        return this;
      }
      /**
       * <code>string nome_da_func = 4;</code>
       * @param value The bytes for nomeDaFunc to set.
       * @return This builder for chaining.
       */
      public Builder setNomeDaFuncBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        nomeDaFunc_ = value;
        onChanged();
        return this;
      }

      private int valor_ ;
      /**
       * <code>int32 valor = 5;</code>
       * @return The valor.
       */
      public int getValor() {
        return valor_;
      }
      /**
       * <code>int32 valor = 5;</code>
       * @param value The valor to set.
       * @return This builder for chaining.
       */
      public Builder setValor(int value) {
        
        valor_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 valor = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearValor() {
        
        valor_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protobuff.Request)
    }

    // @@protoc_insertion_point(class_scope:protobuff.Request)
    private static final protobuff.RequestOuterClass.Request DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protobuff.RequestOuterClass.Request();
    }

    public static protobuff.RequestOuterClass.Request getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Request>
        PARSER = new com.google.protobuf.AbstractParser<Request>() {
      @java.lang.Override
      public Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Request(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Request> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Request> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public protobuff.RequestOuterClass.Request getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuff.Response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string tipo_da_msg = 1;</code>
     * @return The tipoDaMsg.
     */
    java.lang.String getTipoDaMsg();
    /**
     * <code>string tipo_da_msg = 1;</code>
     * @return The bytes for tipoDaMsg.
     */
    com.google.protobuf.ByteString
        getTipoDaMsgBytes();

    /**
     * <code>string conteudo = 2;</code>
     * @return The conteudo.
     */
    java.lang.String getConteudo();
    /**
     * <code>string conteudo = 2;</code>
     * @return The bytes for conteudo.
     */
    com.google.protobuf.ByteString
        getConteudoBytes();
  }
  /**
   * Protobuf type {@code protobuff.Response}
   */
  public  static final class Response extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protobuff.Response)
      ResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Response.newBuilder() to construct.
    private Response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Response() {
      tipoDaMsg_ = "";
      conteudo_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Response();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              tipoDaMsg_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              conteudo_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuff.RequestOuterClass.internal_static_protobuff_Response_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuff.RequestOuterClass.internal_static_protobuff_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuff.RequestOuterClass.Response.class, protobuff.RequestOuterClass.Response.Builder.class);
    }

    public static final int TIPO_DA_MSG_FIELD_NUMBER = 1;
    private volatile java.lang.Object tipoDaMsg_;
    /**
     * <code>string tipo_da_msg = 1;</code>
     * @return The tipoDaMsg.
     */
    public java.lang.String getTipoDaMsg() {
      java.lang.Object ref = tipoDaMsg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tipoDaMsg_ = s;
        return s;
      }
    }
    /**
     * <code>string tipo_da_msg = 1;</code>
     * @return The bytes for tipoDaMsg.
     */
    public com.google.protobuf.ByteString
        getTipoDaMsgBytes() {
      java.lang.Object ref = tipoDaMsg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tipoDaMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTEUDO_FIELD_NUMBER = 2;
    private volatile java.lang.Object conteudo_;
    /**
     * <code>string conteudo = 2;</code>
     * @return The conteudo.
     */
    public java.lang.String getConteudo() {
      java.lang.Object ref = conteudo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        conteudo_ = s;
        return s;
      }
    }
    /**
     * <code>string conteudo = 2;</code>
     * @return The bytes for conteudo.
     */
    public com.google.protobuf.ByteString
        getConteudoBytes() {
      java.lang.Object ref = conteudo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        conteudo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTipoDaMsgBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, tipoDaMsg_);
      }
      if (!getConteudoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, conteudo_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTipoDaMsgBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, tipoDaMsg_);
      }
      if (!getConteudoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, conteudo_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protobuff.RequestOuterClass.Response)) {
        return super.equals(obj);
      }
      protobuff.RequestOuterClass.Response other = (protobuff.RequestOuterClass.Response) obj;

      if (!getTipoDaMsg()
          .equals(other.getTipoDaMsg())) return false;
      if (!getConteudo()
          .equals(other.getConteudo())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TIPO_DA_MSG_FIELD_NUMBER;
      hash = (53 * hash) + getTipoDaMsg().hashCode();
      hash = (37 * hash) + CONTEUDO_FIELD_NUMBER;
      hash = (53 * hash) + getConteudo().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protobuff.RequestOuterClass.Response parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuff.RequestOuterClass.Response parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuff.RequestOuterClass.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuff.RequestOuterClass.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuff.RequestOuterClass.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuff.RequestOuterClass.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuff.RequestOuterClass.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protobuff.RequestOuterClass.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protobuff.RequestOuterClass.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protobuff.RequestOuterClass.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protobuff.RequestOuterClass.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protobuff.RequestOuterClass.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protobuff.RequestOuterClass.Response prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuff.Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuff.Response)
        protobuff.RequestOuterClass.ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuff.RequestOuterClass.internal_static_protobuff_Response_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuff.RequestOuterClass.internal_static_protobuff_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobuff.RequestOuterClass.Response.class, protobuff.RequestOuterClass.Response.Builder.class);
      }

      // Construct using protobuff.RequestOuterClass.Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        tipoDaMsg_ = "";

        conteudo_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuff.RequestOuterClass.internal_static_protobuff_Response_descriptor;
      }

      @java.lang.Override
      public protobuff.RequestOuterClass.Response getDefaultInstanceForType() {
        return protobuff.RequestOuterClass.Response.getDefaultInstance();
      }

      @java.lang.Override
      public protobuff.RequestOuterClass.Response build() {
        protobuff.RequestOuterClass.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public protobuff.RequestOuterClass.Response buildPartial() {
        protobuff.RequestOuterClass.Response result = new protobuff.RequestOuterClass.Response(this);
        result.tipoDaMsg_ = tipoDaMsg_;
        result.conteudo_ = conteudo_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuff.RequestOuterClass.Response) {
          return mergeFrom((protobuff.RequestOuterClass.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobuff.RequestOuterClass.Response other) {
        if (other == protobuff.RequestOuterClass.Response.getDefaultInstance()) return this;
        if (!other.getTipoDaMsg().isEmpty()) {
          tipoDaMsg_ = other.tipoDaMsg_;
          onChanged();
        }
        if (!other.getConteudo().isEmpty()) {
          conteudo_ = other.conteudo_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protobuff.RequestOuterClass.Response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protobuff.RequestOuterClass.Response) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object tipoDaMsg_ = "";
      /**
       * <code>string tipo_da_msg = 1;</code>
       * @return The tipoDaMsg.
       */
      public java.lang.String getTipoDaMsg() {
        java.lang.Object ref = tipoDaMsg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          tipoDaMsg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string tipo_da_msg = 1;</code>
       * @return The bytes for tipoDaMsg.
       */
      public com.google.protobuf.ByteString
          getTipoDaMsgBytes() {
        java.lang.Object ref = tipoDaMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tipoDaMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string tipo_da_msg = 1;</code>
       * @param value The tipoDaMsg to set.
       * @return This builder for chaining.
       */
      public Builder setTipoDaMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        tipoDaMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string tipo_da_msg = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTipoDaMsg() {
        
        tipoDaMsg_ = getDefaultInstance().getTipoDaMsg();
        onChanged();
        return this;
      }
      /**
       * <code>string tipo_da_msg = 1;</code>
       * @param value The bytes for tipoDaMsg to set.
       * @return This builder for chaining.
       */
      public Builder setTipoDaMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        tipoDaMsg_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object conteudo_ = "";
      /**
       * <code>string conteudo = 2;</code>
       * @return The conteudo.
       */
      public java.lang.String getConteudo() {
        java.lang.Object ref = conteudo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          conteudo_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string conteudo = 2;</code>
       * @return The bytes for conteudo.
       */
      public com.google.protobuf.ByteString
          getConteudoBytes() {
        java.lang.Object ref = conteudo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          conteudo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string conteudo = 2;</code>
       * @param value The conteudo to set.
       * @return This builder for chaining.
       */
      public Builder setConteudo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        conteudo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string conteudo = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearConteudo() {
        
        conteudo_ = getDefaultInstance().getConteudo();
        onChanged();
        return this;
      }
      /**
       * <code>string conteudo = 2;</code>
       * @param value The bytes for conteudo to set.
       * @return This builder for chaining.
       */
      public Builder setConteudoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        conteudo_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protobuff.Response)
    }

    // @@protoc_insertion_point(class_scope:protobuff.Response)
    private static final protobuff.RequestOuterClass.Response DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protobuff.RequestOuterClass.Response();
    }

    public static protobuff.RequestOuterClass.Response getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Response>
        PARSER = new com.google.protobuf.AbstractParser<Response>() {
      @java.lang.Override
      public Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Response(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Response> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Response> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public protobuff.RequestOuterClass.Response getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuff_Request_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuff_Request_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuff_Response_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuff_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rrequest.proto\022\tprotobuff\"j\n\007Request\022\017\n" +
      "\007comando\030\001 \001(\t\022\023\n\013tipo_da_msg\030\002 \001(\t\022\024\n\014n" +
      "ome_do_disp\030\003 \001(\t\022\024\n\014nome_da_func\030\004 \001(\t\022" +
      "\r\n\005valor\030\005 \001(\005\"1\n\010Response\022\023\n\013tipo_da_ms" +
      "g\030\001 \001(\t\022\020\n\010conteudo\030\002 \001(\tb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_protobuff_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuff_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuff_Request_descriptor,
        new java.lang.String[] { "Comando", "TipoDaMsg", "NomeDoDisp", "NomeDaFunc", "Valor", });
    internal_static_protobuff_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protobuff_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuff_Response_descriptor,
        new java.lang.String[] { "TipoDaMsg", "Conteudo", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
